### ISSUE TITLE
Vacancies - Applications

### ISSUE THREAD

**Issue by MouadOutmane** [MouadOutmane/inetum-realJobs#9]
- [ ] show applications
- [ ] accept or deny an application

**Comment by JohanSchoubben** [comment]
[Search candidates.docx](https://github.com/MouadOutmane/inetum-realJobs/files/7716449/Search.candidates.docx)
[Show applicants.docx](https://github.com/MouadOutmane/inetum-realJobs/files/7716450/Show.applicants.docx)
[View motivation.docx](https://github.com/MouadOutmane/inetum-realJobs/files/7716451/View.motivation.docx)
[View resume.docx](https://github.com/MouadOutmane/inetum-realJobs/files/7716452/View.resume.docx)
